# Generated by Django 5.2.17 on 2026-10-01 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=60)),
                ('target', models.CharField(blank=True, max_length=80)),
                ('detail', models.JSONField(default=dict)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('visited', models.JSONField(default=list)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('name_sw', models.CharField(max_length=60)),
                ('name_en', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'expense categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('reason', models.CharField(max_length=200)),
                ('paid_from', models.CharField(choices=[('droo', 'Till'), ('simu', 'Mobile money'), ('other', 'Other')], max_length=6)),
                ('section', models.CharField(blank=True, choices=[('banda', 'Banda (stall)'), ('mgahawa', 'Mgahawa (restaurant)')], max_length=8)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='core.expensecategory')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.CharField(help_text='yyyy-mm', max_length=7, unique=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rules', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('float_banda', models.BigIntegerField(default=50000)),
                ('float_mgahawa', models.BigIntegerField(default=80000)),
                ('rules', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'settings',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('keshia', 'Cashier'), ('mpishi', 'Cook'), ('mhudumu', 'Waiter'), ('mwingine', 'Other')], max_length=12)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('pay_type', models.CharField(choices=[('daily', 'Daily rate'), ('monthly', 'Monthly salary')], max_length=8)),
                ('rate', models.BigIntegerField()),
                ('day_off', models.PositiveSmallIntegerField(default=1, help_text='0=Sunday ... 6=Saturday')),
                ('joined_on', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('removed_reason', models.CharField(blank=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shortage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('section', models.CharField(blank=True, choices=[('banda', 'Banda (stall)'), ('mgahawa', 'Mgahawa (restaurant)')], max_length=8)),
                ('source', models.CharField(choices=[('cash_count', 'Cash count'), ('manual', 'Written by manager')], max_length=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('waived', 'Waived')], default='applied', max_length=8)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortages', to='core.worker')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('permission', 'Permission'), ('holiday', 'Holiday')], max_length=12)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='core.worker')),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('banda', 'Banda (stall)'), ('mgahawa', 'Mgahawa (restaurant)')], max_length=8)),
                ('amount', models.BigIntegerField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mobile', 'Mobile money')], max_length=6)),
                ('handed_in', models.BooleanField(default=False)),
                ('handed_in_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='core.day')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='core.worker')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Advance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='core.worker')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SalaryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base', models.BigIntegerField()),
                ('advances', models.BigIntegerField()),
                ('shortages', models.BigIntegerField()),
                ('net', models.BigIntegerField()),
                ('stats', models.JSONField(default=dict)),
                ('paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.salaryrun')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_lines', to='core.worker')),
            ],
            options={
                'unique_together': {('run', 'worker')},
            },
        ),
        migrations.CreateModel(
            name='DaySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.CharField(choices=[('banda', 'Banda (stall)'), ('mgahawa', 'Mgahawa (restaurant)')], max_length=8)),
                ('cash', models.BigIntegerField(default=0)),
                ('mobile', models.BigIntegerField(default=0)),
                ('counted', models.BigIntegerField(blank=True, null=True)),
                ('float_amount', models.BigIntegerField(blank=True, null=True)),
                ('difference', models.BigIntegerField(blank=True, help_text='Frozen when the day is closed', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.day')),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.worker')),
            ],
            options={
                'unique_together': {('day', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('late', 'Late'), ('absent', 'Absent')], max_length=8)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='core.worker')),
            ],
            options={
                'unique_together': {('worker', 'date')},
            },
        ),
    ]
