# Generated by Django 5.2.17 on 2026-10-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='day_off',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='0=Sunday ... 6=Saturday; null means no weekly day off', null=True),
        ),
    ]
