# Generated by Django 5.2.17 on 2026-10-03 15:57

from django.db import migrations

# The close-day wizard lost its "Delivery" step (old index 1), so later steps move down by one.
OLD_TO_NEW = {0: 0, 2: 1, 3: 2, 4: 3, 5: 4}


def renumber_visited(apps, schema_editor):
    Day = apps.get_model('core', 'Day')
    for day in Day.objects.all():
        if not day.visited:
            continue
        day.visited = sorted({OLD_TO_NEW[i] for i in day.visited if i in OLD_TO_NEW})
        day.save(update_fields=['visited'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_worker_day_off'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Delivery',
        ),
        migrations.RunPython(renumber_visited, migrations.RunPython.noop),
    ]
