# Generated by Django 5.2.17 on 2026-10-05 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# The close-day wizard gained a "Malipo" step after "Matumizi" (new index 2), so later steps move up by one.
OLD_TO_NEW = {0: 0, 1: 1, 2: 3, 3: 4, 4: 5}


def renumber_visited(apps, schema_editor):
    Day = apps.get_model('core', 'Day')
    for day in Day.objects.all():
        if not day.visited:
            continue
        day.visited = sorted({OLD_TO_NEW[i] for i in day.visited if i in OLD_TO_NEW})
        day.save(update_fields=['visited'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_delivery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('paid_from', models.CharField(choices=[('droo', 'Till'), ('simu', 'Mobile money'), ('other', 'Other')], max_length=6)),
                ('section', models.CharField(blank=True, choices=[('banda', 'Banda (stall)'), ('mgahawa', 'Mgahawa (restaurant)')], max_length=8)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_payments', to='core.worker')),
            ],
            options={
                'ordering': ['date', 'id'],
                'unique_together': {('worker', 'date')},
            },
        ),
        migrations.RunPython(renumber_visited, migrations.RunPython.noop),
    ]
