# Generated by Django 5.2.17 on 2026-10-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_daily_payments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('customer', 'Customer'), ('worker', 'Worker')], max_length=8)),
                ('topic', models.CharField(choices=[('food', 'Food'), ('service', 'Service'), ('cleanliness', 'Cleanliness'), ('price', 'Price'), ('other', 'Other')], default='other', max_length=12)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='1 to 5 stars, optional', null=True)),
                ('message', models.TextField(max_length=1000)),
                ('contact', models.CharField(blank=True, help_text='Optional name or phone; empty means anonymous', max_length=100)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
