# Generated by Django 5.2.17 on 2026-10-05 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_opinions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailypayment',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='shortage',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
